- name: ansible data types 
  hosts: localhost
  vars:
  - AGE: 37 #Number
  - NAME: "srivijay" #String
  - isHero: true #boolean
  - Skills: #list
    - DevOps
      - Git,Jenkins,Docker,K8s,nexus,Sonarkube
    - AWS
      - IAM,EC2,USERDATA,ASG,ALB,ROUTE-53,S3,
    
  - EXPERIENCE: #map
      DevOps: 5
      AWS: 5
  tasks:
  - name: print number variable
    ansible.builtin.debug:
      msg: "{{AGE}}"
  - name: print String variable
    ansible.builtin.debug:
      msg: "{{NAME}}"
  - name: print Boolean variable
    ansible.builtin.debug:
      msg: "{{isHero}}"
  - name: print List variable
    ansible.builtin.debug:
      msg: "{{Skills}}"
  - name: print Map variable
    ansible.builtin.debug:
      msg: "{{EXPERIENCE}}"